name: Release

on:
  release:
    types: [published]

jobs:
  build_and_release:
    runs-on: windows-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: Workflow/Client

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main  # Explicitly check out the main branch 

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Publish Client
        run: dotnet publish Client.csproj -c Release --self-contained true -r win-x64 -o ./client

      - name: Compress Client Build into tar.gz
        run: tar.exe -czf client-${{ github.event.release.tag_name }}.tar.gz -C ./client .
        shell: bash
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: Workflow/Client/client-${{ github.event.release.tag_name }}.tar.gz
          asset_name: client-${{ github.event.release.tag_name }}.tar.gz
          asset_content_type: application/gzip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}